# Generated by Django 3.0.7 on 2020-07-19 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', help_text='missing reason', max_length=255, verbose_name='reason')),
                ('isMissing', models.CharField(default=True, help_text='missing True or False', max_length=255, verbose_name='reason')),
                ('date', models.CharField(help_text='missing date', max_length=255, null=True, verbose_name='date')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lycee.Student')),
            ],
        ),
    ]
