# Generated by Django 3.0.7 on 2020-08-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0002_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='isMissing',
            field=models.BooleanField(verbose_name='Missing'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='reason',
            field=models.CharField(blank=True, default=' ', help_text='missing reason', max_length=255, verbose_name='Reason'),
        ),
        migrations.CreateModel(
            name='CallOfRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(help_text='missing date', max_length=255, null=True, verbose_name='date')),
                ('startTime', models.CharField(help_text='missing date', max_length=255, null=True, verbose_name='Start Time')),
                ('endTime', models.CharField(help_text='missing date', max_length=255, null=True, verbose_name='End Time')),
                ('isPresent', models.BooleanField(verbose_name='Missing')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lycee.Student')),
            ],
        ),
    ]
