# Generated by Django 3.0.7 on 2020-08-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0005_auto_20200827_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='callofroll',
            name='afternoon',
            field=models.BooleanField(default=True, verbose_name='Afternoon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callofroll',
            name='morning',
            field=models.BooleanField(default=False, verbose_name='Morning'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callofroll',
            name='date',
            field=models.DateField(max_length=255, null=True, verbose_name='date'),
        ),
    ]
