# Generated by Django 3.0.7 on 2020-08-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0007_auto_20200827_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='isMissing',
        ),
        migrations.AddField(
            model_name='presence',
            name='dayhalf',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon')], default='1', max_length=9),
        ),
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(help_text='missing date', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='comments',
            field=models.CharField(blank=True, help_text='some comments about the student', max_length=255, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(help_text='last name of the student', max_length=255, verbose_name='lastname'),
        ),
    ]
